name: skypay_sdk
description: Seamless payment integration for Flutter with SkyPay SDK – Simplify and secure payments in your apps effortlessly.
version: 0.0.6
homepage: https://skypay.dev
repository: https://github.com/skybaseinnovations/skypay-sdk
issue_tracker: https://github.com/skybaseinnovations/skypay-sdk/issues

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.2.3
  intl: ^0.19.0
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
